#!/usr/bin/env bash
# Generate a flow-rate calibration print: a 3x3 grid of solid patches, each
# extruded at a different flow percentage, and upload it to the printer.
#
# WHY THIS IS GENERATED AND NOT SLICED. OrcaSlicer ships this exact test
# (Calibration -> Flow rate) and its model lives at
# resources/calib/filament_flow/flowrate-test-pass1.3mf - but the model file
# carries GEOMETRY ONLY. The per-object flow modifiers are injected by the GUI
# wizard at runtime, so slicing that 3mf from the command line yields nine
# identical patches and measures nothing. Driving the CLI was tried and
# abandoned after it began failing with an empty error message; the preset
# chain also has to be flattened first, because `--load-settings` does NOT walk
# "inherits" - it loads exactly the file it is handed, and an OrcaSlicer user
# preset is only a thin override layer over its parents.
#
# HOW TO READ THE RESULT. Look at the TOP surface of each patch under a light.
# Too little flow leaves visible gaps between the infill lines; too much leaves
# ridges, a rough or glossy-scarred surface, and material pushed up at the
# edges. The best patch is the smoothest and flattest one. Its percentage,
# divided by 100 and multiplied by the CURRENT flow ratio, is the new flow
# ratio for this filament.
#
# LAYOUT, viewed from the front of the machine (+Y goes away from you):
#
#     back    110%   115%   120%
#     middle   95%   100%   105%
#     front    80%    85%    90%
#             left  centre  right
#
# The patches are deliberately unlabelled: embossing digits would need a mesh,
# and a 3x3 grid with a fixed map is unambiguous enough to photograph.
#
# Usage: bash scripts/gen-flow-test.sh [outfile]
#
# SAFETY: begins with PRINT_START, which homes. The bed must be CLEAR - Z
# homing raises the bed toward the nozzle and stops on the switch, not on an
# obstacle. Check with the webcam first:
#   curl -s -o bed.jpg "http://192.168.11.160/webcam/?action=snapshot"
set -euo pipefail

OUT="${1:-flowtest.gcode}"
# NOT named PRINTER: Windows already exports PRINTER as the default paper
# printer ("Pantum-E75CB3 (P2500W series)"), which scp then took for a hostname.
PRINTER_SSH="${PRINTER_SSH:-ultra@192.168.11.160}"

awk 'BEGIN{
  PI = 3.14159265358979
  # --- geometry -----------------------------------------------------------
  size = 25          # patch edge, mm
  gap  = 10          # clear space between patches, mm
  pitch = size + gap
  cx = 122; cy = 95  # bed centre-ish (bed is 245 x 190)
  x0 = cx - (3*size + 2*gap)/2
  y0 = cy - (3*size + 2*gap)/2
  # --- extrusion ----------------------------------------------------------
  fil = 1.75
  fil_area = PI * (fil/2)^2
  nlayers = 5
  # --- speeds (mm/min) ----------------------------------------------------
  f_first = 1500     # 25 mm/s on the first layer
  f_print = 3600     # 60 mm/s - slow enough that the surface shows flow, not
                     # melt limits; this test must not be flow-rate limited
  f_trav  = 9000     # 150 mm/s travel, well under the machine ceiling
  retract = 0.8; f_ret = 1800; hop = 0.8

  print "; FLOW RATE CALIBRATION - 3x3 patches, 80%..120% in 5% steps"
  print "; generated by scripts/gen-flow-test.sh - see that file for how to read it"
  print "M83"                     # relative E
  print "PRINT_START EXTRUDER=255 BED=80"
  print "G90"
  print "SET_VELOCITY_LIMIT ACCEL=3000"

  for (L = 0; L < nlayers; L++) {
    if (L == 0) { z = 0.25; h = 0.25; w = 0.7;  fp = f_first }
    else        { z = 0.25 + 0.2*L; h = 0.2; w = 0.6; fp = f_print }
    # extrusion cross-section: rectangle with semicircular ends
    xsec = h*(w - h) + PI*(h/2)^2
    epm  = xsec / fil_area
    printf ";LAYER:%d Z=%.2f\n", L, z

    for (idx = 0; idx < 9; idx++) {
      r = int(idx/3); c = idx % 3
      flow = 80 + 5*idx
      px = x0 + c*pitch; py = y0 + r*pitch
      printf "; --- patch %d  flow %d%% ---\n", idx+1, flow
      printf "M221 S%d\n", flow

      inset = w/2
      ax = px + inset; ay = py + inset
      bx = px + size - inset; by = py + size - inset

      printf "G1 E-%.3f F%d\n", retract, f_ret
      printf "G1 Z%.3f F1200\n", z + hop
      printf "G1 X%.3f Y%.3f F%d\n", ax, ay, f_trav
      printf "G1 Z%.3f F1200\n", z
      printf "G1 E%.3f F%d\n", retract, f_ret

      # one perimeter, so the edges are crisp and the infill has something to
      # tie into - a bare infill block frays and is harder to judge
      printf "G1 X%.3f Y%.3f E%.5f F%d\n", bx, ay, (bx-ax)*epm, fp
      printf "G1 X%.3f Y%.3f E%.5f\n", bx, by, (by-ay)*epm
      printf "G1 X%.3f Y%.3f E%.5f\n", ax, by, (bx-ax)*epm
      printf "G1 X%.3f Y%.3f E%.5f\n", ax, ay, (by-ay)*epm

      # solid infill, direction alternating per layer
      lo = inset + w; hi = size - inset - w
      n = int((hi - lo)/w) + 1
      if (n < 2) n = 2
      step = (hi - lo)/(n - 1)
      for (i = 0; i < n; i++) {
        if (L % 2 == 0) {                      # lines along X
          yy = py + lo + i*step
          if (i % 2 == 0) { sx = px + lo; ex = px + hi } else { sx = px + hi; ex = px + lo }
          printf "G1 X%.3f Y%.3f F%d\n", sx, yy, f_trav
          printf "G1 X%.3f Y%.3f E%.5f F%d\n", ex, yy, (ex>sx ? ex-sx : sx-ex)*epm, fp
        } else {                               # lines along Y
          xx = px + lo + i*step
          if (i % 2 == 0) { sy = py + lo; ey = py + hi } else { sy = py + hi; ey = py + lo }
          printf "G1 X%.3f Y%.3f F%d\n", xx, sy, f_trav
          printf "G1 X%.3f Y%.3f E%.5f F%d\n", xx, ey, (ey>sy ? ey-sy : sy-ey)*epm, fp
        }
      }
    }
  }
  print "M221 S100"
  print "PRINT_END"
}' > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
scp "$OUT" "$PRINTER_SSH:printer_data/gcodes/$(basename "$OUT")"
echo "uploaded. start with:"
echo "  curl -X POST http://192.168.11.160:7125/printer/print/start \\"
echo "    -H 'Content-Type: application/json' -d '{\"filename\":\"$(basename "$OUT")\"}'"
