#!/usr/bin/env bash
# Generate a MAXIMUM VOLUMETRIC FLOW test: a ladder of long single lines, each
# extruded at a higher mm3/s than the last, and upload it to the printer.
#
# WHY THIS IS A DIFFERENT TEST FROM scripts/gen-flow-test.sh. That one varies the
# flow PERCENTAGE at a fixed speed and answers "is the extrusion multiplier
# right" - a calibration of accuracy. This one varies the VOLUMETRIC RATE and
# answers "how fast can this hotend melt plastic at all" - a limit of the
# hardware. They are unrelated numbers and neither substitutes for the other.
#
# WHY IT MATTERS HERE. On 2026-08-18 the motors were shown to hold 300mm/s on
# both axes, and the print speed was still capped at 98mm/s - by
# filament_max_volumetric_speed = 10 in the filament profile. That 10 is the
# generic PETG default, not a measurement of this Volcano. Until the real figure
# is known, the machine's top speed is set by a guess.
#
# HOW TO READ THE RESULT. The lines are printed in order, front to back, slowest
# first. Walk along them: while the melt keeps up, every line looks the same. The
# first line that turns thin, matte, rough, or breaks into a dotted trail is
# where the hotend ran out - the melt is no longer keeping pace with the feed.
# Take the LAST GOOD line's rate, not the first bad one, and subtract ~10-15% for
# margin. That is filament_max_volumetric_speed.
#
# The rate for each line is printed to the console via M117 as it starts, and
# also written as a comment before each line, so a photograph plus this file is
# enough to identify them.
#
# ⚠️ WHY THE LINES ARE LONG. Reachable peak velocity is sqrt(a*L*(1-min_cruise));
# at 4000mm/s^2 over a 30mm feature that is only ~245mm/s, so a small test would
# silently never reach the speeds the top rungs ask for - the axis would spend
# the whole line accelerating. At 180mm the ceiling is ~600mm/s, well clear.
# This is the same trap the circles rig fell into (docs/motor-tuning-results.md,
# "Правило стенда").
#
# ⚠️ FIRST LAYER ONLY, ON PURPOSE. Every line goes down on bare bed at the same
# Z, so they are directly comparable and the test costs one layer of plastic.
# Bed adhesion is not the subject here; a line that lifts is still readable.
#
# Usage: bash scripts/gen-maxflow-test.sh [outfile]
#   FLOW_MIN / FLOW_MAX / STEPS override the ladder (mm3/s).
#
# SAFETY: begins with PRINT_START, which homes. The bed must be CLEAR - Z homing
# raises the bed toward the nozzle and stops on the switch, not on an obstacle.
# Check with the webcam first:
#   curl -s -o bed.jpg "http://192.168.11.160/webcam/?action=snapshot"
# 🔴 And do not run this until H18 is resolved: the extruder thermistor is held
# in its hole by thermal paste alone and loses contact under motion, reading LOW
# - which makes Klipper heat harder. This test is minutes of continuous fast
# extrusion at 255C.
set -euo pipefail

OUT="${1:-maxflow.gcode}"
# NOT named PRINTER: Windows already exports PRINTER as the default paper printer.
PRINTER_SSH="${PRINTER_SSH:-ultra@192.168.11.160}"

FLOW_MIN="${FLOW_MIN:-6}"
FLOW_MAX="${FLOW_MAX:-34}"
STEPS="${STEPS:-12}"

awk -v fmin="$FLOW_MIN" -v fmax="$FLOW_MAX" -v steps="$STEPS" 'BEGIN{
  PI = 3.14159265358979
  # --- geometry -----------------------------------------------------------
  h = 0.2                 # layer height
  w = 0.62                # line width for a 0.6 nozzle
  fil = 1.75
  xsec = h*(w - h) + PI*(h/2)^2          # extrusion cross-section, mm^2
  epm  = xsec / (PI*(fil/2)^2)           # filament mm per mm of travel
  len   = 180             # line length - long enough to actually reach speed
  x0    = 30              # bed is 245 x 190; leaves margin on both sides
  y0    = 25
  pitch = 10              # gap between lines, wide enough to judge each alone
  vmax  = 300             # machine ceiling, mm/s - never command past it

  printf "; MAXIMUM VOLUMETRIC FLOW test - %d lines, %g..%g mm3/s\n", steps, fmin, fmax
  print  "; generated by scripts/gen-maxflow-test.sh - read that file for how to judge it"
  printf "; layer %.2f, width %.2f, cross-section %.4f mm^2\n", h, w, xsec
  print  "M83"
  print  "PRINT_START EXTRUDER=255 BED=80"
  print  "G90"
  print  "SET_VELOCITY_LIMIT ACCEL=4000"

  capped = 0
  for (i = 0; i < steps; i++) {
    flow = fmin + (fmax - fmin) * i / (steps - 1)
    v    = flow / xsec                    # mm/s needed to move that volume
    if (v > vmax) { v = vmax; flow = v * xsec; capped++ }
    y = y0 + i*pitch

    printf "; --- line %d: %.1f mm3/s at %.0f mm/s ---\n", i+1, flow, v
    printf "M117 %.1f mm3/s\n", flow
    print  "G1 E-0.8 F1800"
    printf "G1 Z%.2f F1200\n", h + 0.8
    printf "G1 X%.1f Y%.1f F9000\n", x0, y
    printf "G1 Z%.2f F1200\n", h
    print  "G1 E0.8 F1800"
    # A short lead-in at a safe rate: the pressure in the nozzle has to build
    # before the line being judged starts, or the first millimetres are thin for
    # reasons that have nothing to do with the melt limit.
    printf "G1 X%.1f Y%.1f E%.5f F%d\n", x0+15, y, 15*epm, 2400
    printf "G1 X%.1f Y%.1f E%.5f F%d\n", x0+len, y, (len-15)*epm, v*60
  }
  print "G1 E-0.8 F1800"
  print "M117 maxflow done"
  print "PRINT_END"
  if (capped > 0)
    printf "; NOTE: %d top rung(s) clamped to the %g mm/s machine ceiling - the ladder\n; stops testing higher flow there. Raise layer height to probe further.\n", capped, vmax
}' > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
grep -c "^M117 " "$OUT" | xargs echo "  rungs:"
grep "^; NOTE:" "$OUT" || true
scp "$OUT" "$PRINTER_SSH:printer_data/gcodes/$(basename "$OUT")"
echo "uploaded. start with:"
echo "  curl -X POST http://192.168.11.160:7125/printer/print/start \\"
echo "    -H 'Content-Type: application/json' -d '{\"filename\":\"$(basename "$OUT")\"}'"
